In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1117, 9646, 9737, 5574],
 [1117, 9646, 9737, 8698],
 [1117, 2744, 9737, 6957],
 [8756, 738, 3220, 4391, 1804],
 [8756, 738, 3220, 4391, 7331],
 [4827, 1117, 9308, 9737, 6020],
 [4255, 5668, 7325, 4391]]

In [5]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding

from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np
sent_length=8
embed_docs=pad_sequences(one_hot_repr,padding='pre',
maxlen=sent_length)
print(embed_docs)

[[   0    0    0    0 1117 9646 9737 5574]
 [   0    0    0    0 1117 9646 9737 8698]
 [   0    0    0    0 1117 2744 9737 6957]
 [   0    0    0 8756  738 3220 4391 1804]
 [   0    0    0 8756  738 3220 4391 7331]
 [   0    0    0 4827 1117 9308 9737 6020]
 [   0    0    0    0 4255 5668 7325 4391]]


In [7]:
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
model.predict(embed_docs)

1/1 [==============================] - 0s 132ms/step


array([[[-0.04824077, -0.01692433, -0.02147843,  0.04190746,
         -0.04381578,  0.03817428, -0.00095683, -0.01516833,
          0.00836958,  0.02753351],
        [-0.04824077, -0.01692433, -0.02147843,  0.04190746,
         -0.04381578,  0.03817428, -0.00095683, -0.01516833,
          0.00836958,  0.02753351],
        [-0.04824077, -0.01692433, -0.02147843,  0.04190746,
         -0.04381578,  0.03817428, -0.00095683, -0.01516833,
          0.00836958,  0.02753351],
        [-0.04824077, -0.01692433, -0.02147843,  0.04190746,
         -0.04381578,  0.03817428, -0.00095683, -0.01516833,
          0.00836958,  0.02753351],
        [-0.00483244,  0.03875468,  0.01517279,  0.02233723,
          0.01518199, -0.01479145,  0.03845305, -0.01731223,
         -0.04474794,  0.03688195],
        [-0.00842388,  0.03184129,  0.01953599,  0.01841522,
         -0.0486861 ,  0.03112743, -0.04352355,  0.04661362,
          0.04597522,  0.00910609],
        [ 0.02682846, -0.03820201, -0.03984427, -0.0